package libraryapplication;

import databaselayer.Const;
import java.sql.*;
import javax.swing.JOptionPane;

public class AddBook extends javax.swing.JFrame {
    private Connection connect;
    
    public AddBook() {
        initComponents();
    }

    public AddBook(Connection myConnect) {
        initComponents(); 
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setVisible(true); 
        connect = myConnect;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPanel = new javax.swing.JPanel();
        LabelName = new javax.swing.JLabel();
        LabelAuthor = new javax.swing.JLabel();
        LabelPublisher = new javax.swing.JLabel();
        LabelPublisherYear = new javax.swing.JLabel();
        LabelNumInstan = new javax.swing.JLabel();
        LabelCostBook = new javax.swing.JLabel();
        LabelVolumeBook = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        FieldPanel = new javax.swing.JPanel();
        FieldName = new javax.swing.JTextField();
        FieldAuthor = new javax.swing.JTextField();
        FieldPublisher = new javax.swing.JTextField();
        FieldPublisherYear = new javax.swing.JTextField();
        FieldNumInstan = new javax.swing.JTextField();
        FieldCostBook = new javax.swing.JTextField();
        FieldVolumeBook = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Добавление новой книги");
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        LabelPanel.setBackground(new java.awt.Color(255, 255, 204));
        LabelPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        LabelPanel.setLayout(new java.awt.GridLayout(8, 0));

        LabelName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelName.setText("Название");
        LabelPanel.add(LabelName);

        LabelAuthor.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelAuthor.setText("Автор (Фамилия И.О.)");
        LabelPanel.add(LabelAuthor);

        LabelPublisher.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelPublisher.setText("Издательство");
        LabelPanel.add(LabelPublisher);

        LabelPublisherYear.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelPublisherYear.setText("Год издания");
        LabelPanel.add(LabelPublisherYear);

        LabelNumInstan.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelNumInstan.setText("Кол-во экземпляров");
        LabelPanel.add(LabelNumInstan);

        LabelCostBook.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelCostBook.setText("Цена одного издания");
        LabelPanel.add(LabelCostBook);

        LabelVolumeBook.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelVolumeBook.setText("Кол-во страниц");
        LabelPanel.add(LabelVolumeBook);

        Add.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        Add.setText("Добавить");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        LabelPanel.add(Add);

        getContentPane().add(LabelPanel);

        FieldPanel.setBackground(new java.awt.Color(255, 255, 204));
        FieldPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        FieldPanel.setLayout(new java.awt.GridLayout(8, 0));

        FieldName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldName);

        FieldAuthor.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldAuthor);

        FieldPublisher.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldPublisher);

        FieldPublisherYear.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldPublisherYear);

        FieldNumInstan.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldNumInstan);

        FieldCostBook.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldCostBook);

        FieldVolumeBook.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldVolumeBook);

        Cancel.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        Cancel.setText("Отмена");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        FieldPanel.add(Cancel);

        getContentPane().add(FieldPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // формирование запроса на добавление строки в БД
        String query = "INSERT INTO " + Const.BOOKS_TABLE + "(" + Const.BOOKS_NAME 
                + ", " + Const.BOOKS_AUTHOR + ", " + Const.BOOKS_PUBLISHER 
                + ", " + Const.BOOKS_PUBLISHER_YEAR + ", " + Const.BOOKS_NUM_INSTAN 
                + ", " + Const.BOOKS_COST + ", " + Const.BOOKS_VOLUME + ") VALUES('"
                + FieldName.getText() + "', '"          // название книги
                + FieldAuthor.getText() + "', '"        // имя автора
                + FieldPublisher.getText() + "', '"     // издательство
                + FieldPublisherYear.getText() + "', '" // год издания
                + FieldNumInstan.getText() + "', '"     // кол-во изданий
                + FieldCostBook.getText() + "', '"      // цена книги
                + FieldVolumeBook.getText() + "')";     // кол-во страниц
        try {
            Statement stmt = connect.createStatement();
            int rs = stmt.executeUpdate(query);
            this.dispose();
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, " Добавление новой записи в БД "
                    + "невозможна! /n Can't add new record!");
            this.dispose();
        }
    }//GEN-LAST:event_AddActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField FieldAuthor;
    private javax.swing.JTextField FieldCostBook;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldNumInstan;
    private javax.swing.JPanel FieldPanel;
    private javax.swing.JTextField FieldPublisher;
    private javax.swing.JTextField FieldPublisherYear;
    private javax.swing.JTextField FieldVolumeBook;
    private javax.swing.JLabel LabelAuthor;
    private javax.swing.JLabel LabelCostBook;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelNumInstan;
    private javax.swing.JPanel LabelPanel;
    private javax.swing.JLabel LabelPublisher;
    private javax.swing.JLabel LabelPublisherYear;
    private javax.swing.JLabel LabelVolumeBook;
    // End of variables declaration//GEN-END:variables
}
