package libraryapplication;

import businesslogiclayer.ValidationValues;
import databaselayer.Const;
import businesslogiclayer.Reader;
import java.sql.*;
import javax.swing.JOptionPane;

public class AddReader extends javax.swing.JFrame {
    private Connection connect;
    
    public AddReader() {
        initComponents();
    }

    public AddReader(Connection myConnect) {
        initComponents(); 
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setVisible(true); 
        connect = myConnect;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPanel = new javax.swing.JPanel();
        LabelFirstName = new javax.swing.JLabel();
        LabelLastName = new javax.swing.JLabel();
        LabelPatronymic = new javax.swing.JLabel();
        LabelAddress = new javax.swing.JLabel();
        LabelPhone = new javax.swing.JLabel();
        LabelNumberAccount = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        FieldPanel = new javax.swing.JPanel();
        FieldFirstName = new javax.swing.JTextField();
        FieldLastName = new javax.swing.JTextField();
        FieldPatronymic = new javax.swing.JTextField();
        FieldAddress = new javax.swing.JTextField();
        FieldPhone = new javax.swing.JFormattedTextField();
        FieldNumberAccount = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        LabelPanel.setBackground(new java.awt.Color(255, 255, 204));
        LabelPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        LabelPanel.setLayout(new java.awt.GridLayout(7, 0));

        LabelFirstName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelFirstName.setText("Фамилия");
        LabelPanel.add(LabelFirstName);

        LabelLastName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelLastName.setText("Имя");
        LabelPanel.add(LabelLastName);

        LabelPatronymic.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelPatronymic.setText("Отчество");
        LabelPanel.add(LabelPatronymic);

        LabelAddress.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelAddress.setText("Адрес");
        LabelPanel.add(LabelAddress);

        LabelPhone.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelPhone.setText("Номер телефона");
        LabelPanel.add(LabelPhone);

        LabelNumberAccount.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelNumberAccount.setText("Номер читательского билета");
        LabelPanel.add(LabelNumberAccount);

        Add.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        Add.setText("Добавить");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        LabelPanel.add(Add);

        getContentPane().add(LabelPanel);

        FieldPanel.setBackground(new java.awt.Color(255, 255, 204));
        FieldPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        FieldPanel.setLayout(new java.awt.GridLayout(7, 0));

        FieldFirstName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldFirstName);

        FieldLastName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldLastName);

        FieldPatronymic.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldPatronymic);

        FieldAddress.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldAddress);

        try {
            FieldPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+7(###)###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FieldPhone.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPhone.setPreferredSize(new java.awt.Dimension(300, 30));
        FieldPanel.add(FieldPhone);

        FieldNumberAccount.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldNumberAccount);

        Cancel.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        Cancel.setText("Отмена");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        FieldPanel.add(Cancel);

        getContentPane().add(FieldPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        ValidationValues value = new ValidationValues();
        try {
            value.Telephone(FieldPhone.getText());
            value.NumberAccount(FieldNumberAccount.getText());
            if (!FieldFirstName.equals("") || !FieldLastName.equals("") || 
                    !FieldPatronymic.equals("") || !FieldAddress.equals("")) {
                String firstName = FieldFirstName.getText();
                String lastName = FieldLastName.getText();
                String patronymic = FieldPatronymic.getText();
                String address = FieldAddress.getText();
                String phone = FieldPhone.getText();
                String numberAccount = FieldNumberAccount.getText();
                Reader reader = new Reader(firstName, lastName, 
                        patronymic, address, phone, numberAccount);
                try {
                    additionReader(reader);
                    this.dispose();
                }
                catch(Exception e) {
                    JOptionPane.showMessageDialog(this, " Добавление новой записи в БД "
                        + "невозможна! /n Can't add new record!");
                    this.dispose();
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "Некоторые поля пустые!");
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, exception.getMessage());
        }
    }//GEN-LAST:event_AddActionPerformed
    
    public void additionReader(Reader reader) 
            throws ClassNotFoundException, SQLException {
        String fullName = reader.getSurnameAndInitials(reader.getFirstName(), 
                reader.getLastName(), reader.getPatronymic());
        // формирование запроса на добавление строки в БД
        String query = "INSERT INTO " + Const.READERS_TABLE 
                + "(" + Const.READERS_FULLNAME + ", " + Const.READERS_ADDRESS 
                + ", " + Const.READERS_PHONE + ", " + Const.READERS_NUMLIBCARD 
                +  ") VALUES('"
                + fullName + "', '"                  // Фамилия И.О.
                + reader.getAddress() + "', '"       // адресс
                + reader.getPhone() + "', '"         // телефон
                + reader.getNumberAccount() + "')";  // номер книжки
        Statement stmt = connect.createStatement();
        int rs = stmt.executeUpdate(query);
    }
    
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddReader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField FieldAddress;
    private javax.swing.JTextField FieldFirstName;
    private javax.swing.JTextField FieldLastName;
    private javax.swing.JTextField FieldNumberAccount;
    private javax.swing.JPanel FieldPanel;
    private javax.swing.JTextField FieldPatronymic;
    private javax.swing.JFormattedTextField FieldPhone;
    private javax.swing.JLabel LabelAddress;
    private javax.swing.JLabel LabelFirstName;
    private javax.swing.JLabel LabelLastName;
    private javax.swing.JLabel LabelNumberAccount;
    private javax.swing.JPanel LabelPanel;
    private javax.swing.JLabel LabelPatronymic;
    private javax.swing.JLabel LabelPhone;
    // End of variables declaration//GEN-END:variables
}
