package libraryapplication;

import businesslogiclayer.Reader;
import businesslogiclayer.ValidationValues;
import databaselayer.Const;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class EditReader extends javax.swing.JFrame {
    private Connection connect;
    private String id;
    
    public EditReader() {
        initComponents();
    }
    
    public EditReader(Connection myConnect, String selectRow) {
        initComponents();
        id = selectRow; 
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setVisible(true); 
        connect = myConnect; 
        try { 
            Statement stmt = connect.createStatement(); 
            // получим строку с переданным в качестве параметра id и 
            // представим её в виде массива для дальнейшего редактирования 
            ResultSet rs = stmt.executeQuery("SELECT * FROM " + Const.READERS_TABLE 
                    + " WHERE " + Const.READERS_ID + "=" + id); 
            ResultSetMetaData md = rs.getMetaData(); 
            while(rs.next()){ 
                ArrayList<Object> mass = new ArrayList(); 
                for(int i=1;i<=md.getColumnCount();i++) { 
                    mass.add(rs.getObject(i)); 
                } 
                mass.toArray();
                FieldFullName.setText(mass.get(1).toString()); 
                FieldAddress.setText(mass.get(2).toString()); 
                FieldPhone.setText(mass.get(3).toString());
                FieldNumberAccount.setText(mass.get(4).toString());
            } 
        } 
        catch(Exception e) { 
            JOptionPane.showMessageDialog(this, "Error!"); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPanel = new javax.swing.JPanel();
        LabelFullName = new javax.swing.JLabel();
        LabelAddress = new javax.swing.JLabel();
        LabelPhone = new javax.swing.JLabel();
        LabelNumberAccount = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        FieldPanel = new javax.swing.JPanel();
        FieldFullName = new javax.swing.JTextField();
        FieldAddress = new javax.swing.JTextField();
        FieldPhone = new javax.swing.JFormattedTextField();
        FieldNumberAccount = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Редактирование читателя");
        setPreferredSize(new java.awt.Dimension(500, 200));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        LabelPanel.setBackground(new java.awt.Color(255, 255, 204));
        LabelPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        LabelPanel.setLayout(new java.awt.GridLayout(5, 0));

        LabelFullName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelFullName.setText("Фамилия И.О.");
        LabelPanel.add(LabelFullName);

        LabelAddress.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelAddress.setText("Адрес");
        LabelPanel.add(LabelAddress);

        LabelPhone.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelPhone.setText("Номер телефона");
        LabelPanel.add(LabelPhone);

        LabelNumberAccount.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelNumberAccount.setText("№ читательского билета");
        LabelPanel.add(LabelNumberAccount);

        Edit.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        Edit.setText("Подтверждение");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        LabelPanel.add(Edit);

        getContentPane().add(LabelPanel);

        FieldPanel.setBackground(new java.awt.Color(255, 255, 204));
        FieldPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        FieldPanel.setLayout(new java.awt.GridLayout(5, 0));

        FieldFullName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldFullName);

        FieldAddress.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldAddress);

        try {
            FieldPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+7(###)###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FieldPhone.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPhone.setPreferredSize(new java.awt.Dimension(300, 30));
        FieldPanel.add(FieldPhone);

        FieldNumberAccount.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldNumberAccount);

        Cancel.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        Cancel.setText("Отмена");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        FieldPanel.add(Cancel);

        getContentPane().add(FieldPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        ValidationValues value = new ValidationValues();
        try {
            value.Telephone(FieldPhone.getText());
            value.NumberAccount(FieldNumberAccount.getText());
            if (!FieldFullName.equals("") || !FieldAddress.equals("")) {
                String fullName = FieldFullName.getText();
                String address = FieldAddress.getText();
                String phone = FieldPhone.getText();
                String numberAccount = FieldNumberAccount.getText();
                Reader reader = new Reader(fullName, address, phone, numberAccount);
                try {
                    updateReader(reader);
                    this.dispose();
                }
                catch(Exception e) {
                    JOptionPane.showMessageDialog(this, " Невозможно редактировать записи "
                        + "об этом читателе! /n Can't edit this reader!");
                    this.dispose();
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "Некоторые поля пустые!");
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, exception.getMessage());
        }
    }//GEN-LAST:event_EditActionPerformed

    private void updateReader(Reader reader) 
            throws ClassNotFoundException, SQLException {
        // формирование запроса на добавление строки в БД
        String query = "UPDATE " + Const.READERS_TABLE + " SET " 
                + Const.READERS_FULLNAME + "='" + FieldFullName.getText() + "', "
                + Const.READERS_ADDRESS + "='" + FieldAddress.getText() + "', "
                + Const.READERS_PHONE + "='" + FieldPhone.getText() + "', "
                + Const.READERS_NUMLIBCARD + "='" + FieldNumberAccount.getText()
                + "' WHERE " + Const.READERS_ID + "=" + id;
        Statement stmt = connect.createStatement();
        int rs = stmt.executeUpdate(query);
    }
    
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditReader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField FieldAddress;
    private javax.swing.JTextField FieldFullName;
    private javax.swing.JTextField FieldNumberAccount;
    private javax.swing.JPanel FieldPanel;
    private javax.swing.JFormattedTextField FieldPhone;
    private javax.swing.JLabel LabelAddress;
    private javax.swing.JLabel LabelFullName;
    private javax.swing.JLabel LabelNumberAccount;
    private javax.swing.JPanel LabelPanel;
    private javax.swing.JLabel LabelPhone;
    // End of variables declaration//GEN-END:variables
}
