package libraryapplication;

import databaselayer.Const;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class EditBook extends javax.swing.JFrame {
    private Connection connect;
    private String id;
    
    public EditBook() {
        initComponents();
    }

    public EditBook(Connection myConnect, String selectRow) {
        initComponents();
        id = selectRow; 
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setVisible(true); 
        connect = myConnect; 
        try { 
            Statement stmt = connect.createStatement(); 
            // получим строку с переданным в качестве параметра id и 
            // представим её в виде массива для дальнейшего редактирования 
            ResultSet rs = stmt.executeQuery("SELECT * FROM " + Const.BOOKS_TABLE 
                    + " WHERE " + Const.BOOKS_ID + "=" + id); 
            ResultSetMetaData md = rs.getMetaData(); 
            while(rs.next()){ 
                ArrayList<Object> mass = new ArrayList(); 
                for(int i=1;i<=md.getColumnCount();i++) { 
                    mass.add(rs.getObject(i)); 
                } 
                mass.toArray();
                FieldName.setText(mass.get(1).toString()); 
                FieldAuthor.setText(mass.get(2).toString()); 
                FieldPublisher.setText(mass.get(3).toString());
                FieldPublisherYear.setText(mass.get(4).toString());
                FieldNumInstan.setText(mass.get(5).toString());
                FieldCostBook.setText(mass.get(6).toString());
                FieldVolumeBook.setText(mass.get(7).toString()); 
            } 
        } 
        catch(Exception e) { 
            JOptionPane.showMessageDialog(this, "Error!"); 
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPanel = new javax.swing.JPanel();
        LabelName = new javax.swing.JLabel();
        LabelAuthor = new javax.swing.JLabel();
        LabelPublisher = new javax.swing.JLabel();
        LabelPublisherYear = new javax.swing.JLabel();
        LabelNumInstan = new javax.swing.JLabel();
        LabelCostBook = new javax.swing.JLabel();
        LabelVolumeBook = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        FieldPanel = new javax.swing.JPanel();
        FieldName = new javax.swing.JTextField();
        FieldAuthor = new javax.swing.JTextField();
        FieldPublisher = new javax.swing.JTextField();
        FieldPublisherYear = new javax.swing.JTextField();
        FieldNumInstan = new javax.swing.JTextField();
        FieldCostBook = new javax.swing.JTextField();
        FieldVolumeBook = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Редактирование книги");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        LabelPanel.setBackground(new java.awt.Color(255, 255, 204));
        LabelPanel.setPreferredSize(new java.awt.Dimension(200, 400));
        LabelPanel.setLayout(new java.awt.GridLayout(8, 0));

        LabelName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelName.setText("Название");
        LabelPanel.add(LabelName);

        LabelAuthor.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelAuthor.setText("Автор (Фамилия И.О.)");
        LabelPanel.add(LabelAuthor);

        LabelPublisher.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelPublisher.setText("Издательство");
        LabelPanel.add(LabelPublisher);

        LabelPublisherYear.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelPublisherYear.setText("Год издания");
        LabelPanel.add(LabelPublisherYear);

        LabelNumInstan.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelNumInstan.setText("Кол-во экземпляров");
        LabelPanel.add(LabelNumInstan);

        LabelCostBook.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelCostBook.setText("Цена одного издания");
        LabelPanel.add(LabelCostBook);

        LabelVolumeBook.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelVolumeBook.setText("Кол-во страниц");
        LabelPanel.add(LabelVolumeBook);

        Edit.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        Edit.setText("Подтверждение");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        LabelPanel.add(Edit);

        getContentPane().add(LabelPanel);

        FieldPanel.setBackground(new java.awt.Color(255, 255, 204));
        FieldPanel.setPreferredSize(new java.awt.Dimension(200, 400));
        FieldPanel.setLayout(new java.awt.GridLayout(8, 0));

        FieldName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldName);

        FieldAuthor.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldAuthor);

        FieldPublisher.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldPublisher);

        FieldPublisherYear.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldPublisherYear);

        FieldNumInstan.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldNumInstan);

        FieldCostBook.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldCostBook);

        FieldVolumeBook.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldVolumeBook);

        Cancel.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        Cancel.setText("Отмена");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        FieldPanel.add(Cancel);

        getContentPane().add(FieldPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // формирование запроса на добавление строки в БД
        String query = "UPDATE " + Const.BOOKS_TABLE + " SET " 
                + Const.BOOKS_NAME + "='" + FieldName.getText() + "', "
                + Const.BOOKS_AUTHOR + "='" + FieldAuthor.getText() + "', "
                + Const.BOOKS_PUBLISHER + "='" + FieldPublisher.getText() + "', "
                + Const.BOOKS_PUBLISHER_YEAR + "='" + FieldPublisherYear.getText() + "', "
                + Const.BOOKS_NUM_INSTAN + "='" + FieldNumInstan.getText() + "', "
                + Const.BOOKS_COST + "='" + FieldCostBook.getText() + "', " 
                + Const.BOOKS_VOLUME + "='" + FieldVolumeBook.getText()
                + "' WHERE " + Const.BOOKS_ID + "=" + id;
        try { // передаем запрос на исполнение
            Statement stmt = connect.createStatement();
            int rs = stmt.executeUpdate(query);
            this.dispose();
        } // и выводим сообщение об ошибке в исключительной ситуации 
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, " Невозможно редактировать записи "
                + "по этой книге! /n Can't edit this book!");
            this.dispose();
        }
    }//GEN-LAST:event_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField FieldAuthor;
    private javax.swing.JTextField FieldCostBook;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldNumInstan;
    private javax.swing.JPanel FieldPanel;
    private javax.swing.JTextField FieldPublisher;
    private javax.swing.JTextField FieldPublisherYear;
    private javax.swing.JTextField FieldVolumeBook;
    private javax.swing.JLabel LabelAuthor;
    private javax.swing.JLabel LabelCostBook;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelNumInstan;
    private javax.swing.JPanel LabelPanel;
    private javax.swing.JLabel LabelPublisher;
    private javax.swing.JLabel LabelPublisherYear;
    private javax.swing.JLabel LabelVolumeBook;
    // End of variables declaration//GEN-END:variables
}
