package libraryapplication;

import businesslogiclayer.ValidationValues;
import databaselayer.Const;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class FindReader extends javax.swing.JFrame {
    private Connection connect;
    private JTable table;
    
    public FindReader() {
        initComponents();
    }

    public FindReader(Connection myConnect, JTable TableView1) {
    // передаем в конструктор объект таблицы с главного меню для отображения результатов поиска 
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setVisible(true); 
        table = TableView1; 
        connect = myConnect;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPanel = new javax.swing.JPanel();
        LabelFullName = new javax.swing.JLabel();
        LabelAddress = new javax.swing.JLabel();
        LabelPhone = new javax.swing.JLabel();
        LabelNumberAccount = new javax.swing.JLabel();
        Find = new javax.swing.JButton();
        FieldPanel = new javax.swing.JPanel();
        FieldFullName = new javax.swing.JTextField();
        FieldAddress = new javax.swing.JTextField();
        FieldPhone = new javax.swing.JFormattedTextField();
        FieldNumberAccount = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Поиск читателя");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        LabelPanel.setBackground(new java.awt.Color(255, 255, 204));
        LabelPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        LabelPanel.setLayout(new java.awt.GridLayout(5, 0));

        LabelFullName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelFullName.setText("Фамилия И.О.");
        LabelPanel.add(LabelFullName);

        LabelAddress.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelAddress.setText("Адрес");
        LabelPanel.add(LabelAddress);

        LabelPhone.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelPhone.setText("Номер телефона");
        LabelPanel.add(LabelPhone);

        LabelNumberAccount.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        LabelNumberAccount.setText("№ читательского билета");
        LabelPanel.add(LabelNumberAccount);

        Find.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        Find.setText("Поиск");
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });
        LabelPanel.add(Find);

        getContentPane().add(LabelPanel);

        FieldPanel.setBackground(new java.awt.Color(255, 255, 204));
        FieldPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        FieldPanel.setLayout(new java.awt.GridLayout(5, 0));

        FieldFullName.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldFullName);

        FieldAddress.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldAddress);

        try {
            FieldPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+7(###)###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FieldPhone.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPhone.setPreferredSize(new java.awt.Dimension(300, 30));
        FieldPanel.add(FieldPhone);

        FieldNumberAccount.setFont(new java.awt.Font("Gungsuh", 0, 14)); // NOI18N
        FieldPanel.add(FieldNumberAccount);

        Cancel.setFont(new java.awt.Font("Gungsuh", 1, 14)); // NOI18N
        Cancel.setText("Отмена");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        FieldPanel.add(Cancel);

        getContentPane().add(FieldPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        // начало формирования запроса. Условие id=id введено искусственно для случая, 
        // когда не будет введено ни одного критерия поиска для отображения всех результатов
        String query = "SELECT * FROM " + Const.READERS_TABLE + " WHERE " 
                + Const.READERS_ID + "=" + Const.READERS_ID;
        // далее – обработка текстовых полей с критериями поиска 
        if(!FieldFullName.getText().isEmpty()) { 
            query += " AND UPPER(" + Const.READERS_FULLNAME + ") LIKE '%"; 
            query += FieldFullName.getText().toUpperCase(); 
            query += "%'"; 
        }
        if(!FieldAddress.getText().isEmpty()) { 
            query += " AND UPPER(" + Const.READERS_ADDRESS + ") LIKE '%"; 
            query += FieldAddress.getText().toUpperCase(); 
            query += "%'"; 
        }
        ValidationValues value = new ValidationValues();
        if(!FieldPhone.getText().equals("+7(   )   -  -  ")) { 
            try { value.Telephone(FieldPhone.getText());
                query += " AND " + Const.READERS_PHONE + " LIKE '%"; 
                query += FieldPhone.getText(); 
                query += "%'"; 
            }
            catch (Exception exception) {
                JOptionPane.showMessageDialog(this, exception.getMessage());
            }
        }
        if(!FieldNumberAccount.getText().isEmpty()) { 
            try { value.NumberAccount(FieldNumberAccount.getText());
                query += " AND " + Const.READERS_NUMLIBCARD + " LIKE '%"; 
                query += FieldNumberAccount.getText(); 
                query += "%'"; 
            }
            catch (Exception exception) {
                JOptionPane.showMessageDialog(this, exception.getMessage());
            }
        }
        // формирование содержимого таблицы с результатами с помощью DefaultTableModel:
        DefaultTableModel model = new DefaultTableModel(); 
        model.setRowCount(0); 
        model.setColumnCount(0);
        try { 
            Statement stmt = connect.createStatement(); 
            ResultSet rs = stmt.executeQuery(query); 
            ResultSetMetaData md = rs.getMetaData(); 
            for(int i=1;i<=md.getColumnCount();i++) { 
                model.addColumn(md.getColumnName(i)); 
            } 
            while(rs.next()){ 
                ArrayList<Object> mass = new ArrayList(); 
                for(int i=1;i<=md.getColumnCount();i++) { 
                    mass.add(rs.getObject(i)); 
                } 
                model.addRow(mass.toArray()); 
            }
            // перенос сформированной таблицы на главную форму проекта для отображения результатов 
            table.setModel(model); 
            this.dispose(); 
        } 
        catch(Exception e) { 
            JOptionPane.showMessageDialog(this, "Error!"); 
            this.dispose(); 
        }
    }//GEN-LAST:event_FindActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindReader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindReader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JTextField FieldAddress;
    private javax.swing.JTextField FieldFullName;
    private javax.swing.JTextField FieldNumberAccount;
    private javax.swing.JPanel FieldPanel;
    private javax.swing.JFormattedTextField FieldPhone;
    private javax.swing.JButton Find;
    private javax.swing.JLabel LabelAddress;
    private javax.swing.JLabel LabelFullName;
    private javax.swing.JLabel LabelNumberAccount;
    private javax.swing.JPanel LabelPanel;
    private javax.swing.JLabel LabelPhone;
    // End of variables declaration//GEN-END:variables
}
