/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryapplication;

import businesslogiclayer.ValidationValues;
import databaselayer.Const;
import businesslogiclayer.Librarian;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Flash
 */
public class RegistrationController extends javax.swing.JFrame {
    private Connection connect;
    
    public RegistrationController() {
        initComponents();
    }

    public RegistrationController(Connection myConnect){
        initComponents(); 
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); 
        setVisible(true); 
        connect = myConnect;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTitle = new javax.swing.JPanel();
        LabelTitle = new javax.swing.JLabel();
        PanelMain = new javax.swing.JPanel();
        PanelForm = new javax.swing.JPanel();
        PanelExtra = new javax.swing.JPanel();
        PanelLabel = new javax.swing.JPanel();
        LabelSurname = new javax.swing.JLabel();
        LabelEmpty1 = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        LabelEmpty2 = new javax.swing.JLabel();
        LabelPatronymic = new javax.swing.JLabel();
        LabelEmpty3 = new javax.swing.JLabel();
        LabelAddress = new javax.swing.JLabel();
        LabelEmpty4 = new javax.swing.JLabel();
        LabelPhone = new javax.swing.JLabel();
        LabelEmpty5 = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        LabelEmpty6 = new javax.swing.JLabel();
        PanelTextField = new javax.swing.JPanel();
        TextSurname = new javax.swing.JTextField();
        LabelHint1 = new javax.swing.JLabel();
        TextName = new javax.swing.JTextField();
        LabelHint2 = new javax.swing.JLabel();
        TextPatronymic = new javax.swing.JTextField();
        LabelHint3 = new javax.swing.JLabel();
        TextAddress = new javax.swing.JTextField();
        LabelHint4 = new javax.swing.JLabel();
        TextPhone = new javax.swing.JFormattedTextField();
        LabelHint5 = new javax.swing.JLabel();
        TextPassword = new javax.swing.JPasswordField();
        LabelHint6 = new javax.swing.JLabel();
        PanelButton = new javax.swing.JPanel();
        BtnRegistration = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 600));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(0, 2));

        PanelTitle.setBackground(new java.awt.Color(204, 204, 0));
        PanelTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        LabelTitle.setFont(new java.awt.Font("GungsuhChe", 2, 24)); // NOI18N
        LabelTitle.setText("Библиотека \"ОмГТУ\"");
        PanelTitle.add(LabelTitle);

        getContentPane().add(PanelTitle, java.awt.BorderLayout.PAGE_START);

        PanelMain.setBackground(new java.awt.Color(255, 255, 204));
        PanelMain.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        PanelForm.setBackground(new java.awt.Color(255, 255, 204));
        PanelForm.setLayout(new javax.swing.BoxLayout(PanelForm, javax.swing.BoxLayout.Y_AXIS));

        PanelExtra.setBackground(new java.awt.Color(255, 255, 204));
        PanelExtra.setLayout(new javax.swing.BoxLayout(PanelExtra, javax.swing.BoxLayout.X_AXIS));

        PanelLabel.setBackground(new java.awt.Color(255, 255, 204));
        PanelLabel.setLayout(new java.awt.GridLayout(12, 0));

        LabelSurname.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        LabelSurname.setText("Фамилия");
        PanelLabel.add(LabelSurname);

        LabelEmpty1.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        PanelLabel.add(LabelEmpty1);

        LabelName.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        LabelName.setText("Имя");
        PanelLabel.add(LabelName);

        LabelEmpty2.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        PanelLabel.add(LabelEmpty2);

        LabelPatronymic.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        LabelPatronymic.setText("Отчество");
        PanelLabel.add(LabelPatronymic);

        LabelEmpty3.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        PanelLabel.add(LabelEmpty3);

        LabelAddress.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        LabelAddress.setText("Адрес");
        PanelLabel.add(LabelAddress);

        LabelEmpty4.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        PanelLabel.add(LabelEmpty4);

        LabelPhone.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        LabelPhone.setText("Телефон");
        PanelLabel.add(LabelPhone);

        LabelEmpty5.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        PanelLabel.add(LabelEmpty5);

        LabelPassword.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        LabelPassword.setText("Пароль");
        PanelLabel.add(LabelPassword);

        LabelEmpty6.setFont(new java.awt.Font("Gungsuh", 1, 24)); // NOI18N
        PanelLabel.add(LabelEmpty6);

        PanelExtra.add(PanelLabel);

        PanelTextField.setBackground(new java.awt.Color(255, 255, 204));
        PanelTextField.setLayout(new java.awt.GridLayout(12, 0));

        TextSurname.setPreferredSize(new java.awt.Dimension(300, 30));
        PanelTextField.add(TextSurname);

        LabelHint1.setFont(new java.awt.Font("Gungsuh", 2, 14)); // NOI18N
        LabelHint1.setForeground(new java.awt.Color(255, 51, 51));
        PanelTextField.add(LabelHint1);

        TextName.setPreferredSize(new java.awt.Dimension(300, 30));
        PanelTextField.add(TextName);

        LabelHint2.setFont(new java.awt.Font("Gungsuh", 2, 14)); // NOI18N
        LabelHint2.setForeground(new java.awt.Color(255, 51, 51));
        PanelTextField.add(LabelHint2);

        TextPatronymic.setPreferredSize(new java.awt.Dimension(300, 30));
        PanelTextField.add(TextPatronymic);

        LabelHint3.setFont(new java.awt.Font("Gungsuh", 2, 14)); // NOI18N
        LabelHint3.setForeground(new java.awt.Color(255, 51, 51));
        PanelTextField.add(LabelHint3);

        TextAddress.setPreferredSize(new java.awt.Dimension(300, 30));
        PanelTextField.add(TextAddress);

        LabelHint4.setFont(new java.awt.Font("Gungsuh", 2, 14)); // NOI18N
        LabelHint4.setForeground(new java.awt.Color(255, 51, 51));
        PanelTextField.add(LabelHint4);

        try {
            TextPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+7(###)###-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextPhone.setPreferredSize(new java.awt.Dimension(300, 30));
        PanelTextField.add(TextPhone);

        LabelHint5.setFont(new java.awt.Font("Gungsuh", 2, 14)); // NOI18N
        LabelHint5.setForeground(new java.awt.Color(255, 51, 51));
        PanelTextField.add(LabelHint5);
        PanelTextField.add(TextPassword);

        LabelHint6.setFont(new java.awt.Font("Gungsuh", 2, 14)); // NOI18N
        LabelHint6.setForeground(new java.awt.Color(255, 51, 51));
        LabelHint6.setText("* размером более 8 символов");
        PanelTextField.add(LabelHint6);

        PanelExtra.add(PanelTextField);

        PanelForm.add(PanelExtra);

        PanelButton.setBackground(new java.awt.Color(255, 255, 204));
        PanelButton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        BtnRegistration.setFont(new java.awt.Font("Gungsuh", 0, 18)); // NOI18N
        BtnRegistration.setText("Зарегистрироваться");
        BtnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrationActionPerformed(evt);
            }
        });
        PanelButton.add(BtnRegistration);

        PanelForm.add(PanelButton);

        PanelMain.add(PanelForm);

        getContentPane().add(PanelMain, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrationActionPerformed
        ValidationValues value = new ValidationValues();
        try {
            value.Telephone(TextPhone.getText());
            value.Email(TextPassword.getText());
            
            String firstName = TextSurname.getText();
            String lastName = TextName.getText();
            String patronymic = TextPatronymic.getText();
            String address = TextAddress.getText();
            String phone = TextPhone.getText();
            String password = TextPassword.getText();
            Librarian librarian = new Librarian(firstName, lastName, 
                    patronymic, address, phone, password);
            try {
                registrationUser(librarian);
                this.dispose(); 
            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "Невозможно добавить пользователя!"); 
                this.dispose(); 
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, exception.getMessage());
        }
    }//GEN-LAST:event_BtnRegistrationActionPerformed

    public void registrationUser(Librarian librarian) 
            throws ClassNotFoundException, SQLException {
        String insert = "INSERT INTO " + Const.LIBRARIAN_TABLE + "(" +
                Const.LIBRARIANS_SURNAME + ", " + Const.LIBRARIANS_NAME + "," +
                Const.LIBRARIANS_PATRONYMIC + ", " + Const.LIBRARIANS_ADDRESS +
                ", " + Const.LIBRARIANS_PHONE + ", " + Const.LIBRARIANS_PASSWORD + 
                ") " + "VALUES(?,?,?,?,?,?)";
        PreparedStatement prSt = connect.prepareStatement(insert);
        prSt.setString(1, librarian.getFirstName());
        prSt.setString(2, librarian.getLastName());
        prSt.setString(3, librarian.getPatronymic());
        prSt.setString(4, librarian.getAddress());
        prSt.setString(5, librarian.getPhone());
        prSt.setString(6, librarian.getPassword());
        prSt.executeUpdate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistration;
    private javax.swing.JLabel LabelAddress;
    private javax.swing.JLabel LabelEmpty1;
    private javax.swing.JLabel LabelEmpty2;
    private javax.swing.JLabel LabelEmpty3;
    private javax.swing.JLabel LabelEmpty4;
    private javax.swing.JLabel LabelEmpty5;
    private javax.swing.JLabel LabelEmpty6;
    private javax.swing.JLabel LabelHint1;
    private javax.swing.JLabel LabelHint2;
    private javax.swing.JLabel LabelHint3;
    private javax.swing.JLabel LabelHint4;
    private javax.swing.JLabel LabelHint5;
    private javax.swing.JLabel LabelHint6;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelPatronymic;
    private javax.swing.JLabel LabelPhone;
    private javax.swing.JLabel LabelSurname;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JPanel PanelButton;
    private javax.swing.JPanel PanelExtra;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JPanel PanelLabel;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelTextField;
    private javax.swing.JPanel PanelTitle;
    private javax.swing.JTextField TextAddress;
    private javax.swing.JTextField TextName;
    private javax.swing.JPasswordField TextPassword;
    private javax.swing.JTextField TextPatronymic;
    private javax.swing.JFormattedTextField TextPhone;
    private javax.swing.JTextField TextSurname;
    // End of variables declaration//GEN-END:variables
}
